name: "subtyping"
description: >-
  Runs in silico subtyping analysis on genome assemblies. Routes assemblies to specific 
  tools based on the organism of interest to determine serotypes, sequence types, virulence, 
  and antimicrobial resistance profiles.
keywords:
  - subtyping
  - serotyping
  - mlst
  - amr
  - taxonomy
  - typing
components:
  - drprg
  - elgato
  - emmtyper
  - json/convert
  - kaptive
  - kleborate
  - meningotype
  - mykrobe
  - ngmaster
  - pbptyper
  - seqsero2
  - seqsero2s
  - serotypefinder
  - shigapass
  - concat/reports
input:
  - ch_myco:
      type: tuple
      description: Channel containing sample metadata and Mycobacterium assemblies
  - ch_gas:
      type: tuple
      description: Channel containing sample metadata and Group A Streptococcus assemblies
  - ch_kleb:
      type: tuple
      description: Channel containing sample metadata and Klebsiella assemblies
  - ch_legionella:
      type: tuple
      description: Channel containing sample metadata and Legionella assemblies
  - ch_strep:
      type: tuple
      description: Channel containing sample metadata and Streptococcus assemblies
  - ch_salmonella:
      type: tuple
      description: Channel containing sample metadata and Salmonella assemblies
  - ch_ecoli:
      type: tuple
      description: Channel containing sample metadata and E. coli / Shigella assemblies
  - ch_vibrio:
      type: tuple
      description: Channel containing sample metadata and Vibrio assemblies
  - ch_gc:
      type: tuple
      description: Channel containing sample metadata and Neisseria gonorrhoeae / meningitidis assemblies
  - ch_acinetobacter:
      type: tuple
      description: Channel containing sample metadata and Acinetobacter assemblies
  - summfle_script:
      type: file
      description: Python script used for summarizing output files (used with EMMTYPER and SEROTYPEFINDER)
  - jsoncon_script:
      type: file
      description: Python script used for JSON conversion (used with DRPRG)
output:
  - for_summary:
      type: file
      description: Combined channel of summary TSV, CSV, and TXT files generated by the various subtyping tools
  - versions:
      type: file
      description: File containing software versions for all executed tools
      pattern: "versions.yml"
authors:
  - "@erinyoung"