name: "taxonomic_profiling"
description: >-
  Rapidly identifies organisms present in sequencing reads and/or assembled FASTA files. 
  Relies heavily on fast, k-mer and MinHash-based algorithms (Kraken2, Mash, Sylph) 
  rather than computationally heavy alignments.
keywords:
  - taxonomy
  - profiling
  - species identification
  - kraken2
  - mash
  - sylph
  - k-mer
  - minhash
components:
  - kraken2
  - mash/dist
  - mash/screen
  - sylph
  - concat/reports
input:
  - ch_reads:
      type: tuple
      description: Channel containing sample metadata and paired-end FASTQ reads
  - ch_fastas:
      type: tuple
      description: Channel containing sample metadata and assembled FASTA files
  - ch_assemblies:
      type: tuple
      description: Channel containing sample metadata and assembled FASTA files (Note/passed into `take` block)
  - ch_kraken2_db:
      type: directory
      description: Channel containing the Kraken2 database directory
  - ch_mash_db:
      type: file
      description: Channel containing the custom MASH database/sketch file
  - ch_sylph_db:
      type: directory
      description: Channel containing the Sylph database file/directory
output:
  - for_ref_download:
      type: file
      description: Combined channel of species identification results (Kraken2, Mash, Sylph) routed to downstream reference downloading processes
  - for_summary:
      type: file
      description: Combined channel of summary CSV/TSV/TXT files generated by Kraken2, Mash, and Sylph
  - for_multiqc:
      type: file
      description: Combined channel of output files routed to MultiQC for reporting (Kraken2 outputs)
  - versions:
      type: file
      description: File containing software versions for all executed tools
      pattern: "versions.yml"
authors:
  - "@erinyoung"