name: Test Grandeur workflow with Klebsiella

on: [pull_request, workflow_dispatch]

jobs:

  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
            
      - name: Clean up Disk space
        uses: jlumbroso/free-disk-space
            
      - name: Install Nextflow
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/

          nextflow -version
          
      - name: Run Grandeur
        run: |
          docker --version
          
          mkdir fastas 
          for accession in GCA_000240185.2_ASM24018v2 GCA_003812925.1_ASM381292v1 GCA_901421005.1_39282_A01
          do
            all=$(echo $accession | cut -f 2 -d "_")
            fir=$(echo $all | cut -c 1-3)
            mid=$(echo $all | cut -c 4-6)
            end=$(echo $all | cut -c 7-9)
            wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/${fir}/${mid}/${end}/${accession}/${accession}_genomic.fna.gz
            gzip -d ${accession}_genomic.fna.gz
            mv ${accession}_genomic.fna fastas/.
          done

          nextflow run . -profile docker -c .github/workflows/github_actions.config --fastas fastas --publish_dir_mode link
          cat grandeur/grandeur_summary.tsv
          cat grandeur/summary/software_versions.yml
          ls  grandeur/multiqc/multiqc_report.html

      - name: Check Klebsiella file
        run: |
          for file in grandeur/kleborate/kleborate_results.tsv
          do
            head $file
            wc -l $file
          done

          
      - name: tree
        run: tree grandeur*
