name: Test Grandeur workflow profile test6

on: [pull_request, workflow_dispatch]

jobs:

  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
            
      - name: Clean up Disk space
        uses: jlumbroso/free-disk-space
            
      - name: Install Nextflow
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/

          nextflow -version
          
      - name: Run Grandeur
        run: |
          nextflow run . -profile docker,test6 -c .github/workflows/github_actions.config --publish_dir_mode link
          
      - name: Check contig files
        run: |
          for file in grandeur/contigs/*_contigs.fa grandeur/grandeur_summary.tsv
          do
            head $file
            wc -l $file
          done      

      - name: tree
        run: tree grandeur*
