name: Test Grandeur workflow profile test

on: [pull_request, workflow_dispatch]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
            
      - name: Clean up Disk space
        uses: jlumbroso/free-disk-space@main
            
      - name: Install Nextflow
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/

          nextflow -version
          
      - name: Run Grandeur
        run: |
          nextflow run . -profile docker,test -c .github/workflows/github_actions.config --publish_dir_mode link
          
      - name: Check files
        run: |
          for file in grandeur/contigs/*_contigs.fa grandeur/grandeur_summary.tsv grandeur/skani/skani_summary.tsv grandeur/fastqc/fastqc_summary.csv grandeur/mlst/mlst_summary.tsv grandeur/plasmidfinder/plasmidfinder_result.json grandeur/quast/quast_report.tsv grandeur/multiqc/multiqc_report.html grandeur/mash/mashdist_summary.csv grandeur/mash/mashscreen_summary.csv
          do
            head $file
            wc -l $file
          done      

      - name: tree
        run: tree grandeur*
