name: Test Grandeur workflow with vibrio

on: [pull_request, workflow_dispatch]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
            
      - name: Clean up Disk space
        uses: jlumbroso/free-disk-space@main
            
      - name: Install Nextflow
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/

          nextflow -version

      - name: Download FASTAS
        run: |
          mkdir fastas
          for accession in GCA_009665515.2_ASM966551v2 GCA_009763645.1_ASM976364v1 GCA_004355205.1_ASM435520v1 GCA_009665315.1_ASM966531v1 GCA_002953375.1_ASM295337v1
          do
            all=$(echo $accession | cut -f 2 -d "_")
            fir=$(echo $all | cut -c 1-3)
            mid=$(echo $all | cut -c 4-6)
            end=$(echo $all | cut -c 7-9)
            wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/$fir/$mid/$end/$accession/${accession}_genomic.fna.gz
            gzip -d ${accession}_genomic.fna.gz
            mv ${accession}_genomic.fna fastas/.
          done

      - name: Run Grandeur
        run: |
          nextflow run . -profile docker -c .github/workflows/github_actions.config --fastas fastas --publish_dir_mode link


      - name: Check Vibrio species
        run: |
          grep -i vibrio grandeur/skani/skani_summary.tsv || { echo "Error: No Vibrio records found."; exit 1; }
          for file in grandeur/grandeur_summary.tsv grandeur/summary/software_versions.yml grandeur/multiqc/multiqc_report.html grandeur/kaptive/kaptive_summary.tsv
          do
            head $file
            wc -l $file
          done
